### ISSUE TITLE
ES6 classes and async await?

### ISSUE THREAD

**Issue by eranimo** [Vincit/moron.js#5]
With Babel we can use these features today. Would it be possible to use moron.js using ES6 classes and async functions instead of promises?

**Comment by koskimas** [comment]
Isn't async functions an ES7 feature? I would have to figure out how Babel "fakes" this feature or rewrite moron.js using ES7 with `async` and `await` keywords. I think ES7 is too far in the future for this.

You can get something similar using the [co library](https://github.com/tj/co) and `--harmony` flag for node. co supports promises so you could do stuff like this:

```js
co(function* () {
  var jennifer = yield Person.query().where('firstName', 'jennifer');
  var children = yield jennifer.$relatedQuery('children');
  return children;
});
```

All the classes in moron.js are written so that the inheritance should work correctly with ES6 classes. I haven't tried this yet, but I'm interested in this also. I will try this in the near future and report my findings.

**Comment by koskimas** [comment]
ES6 classes worked right out of the box. I found one small bug which I will fix immediately. You can define models like this:

```js
class Person extends MoronModel {
  static tableName = 'Person';
  static jsonSchema = {
    type: 'object',
    properties: {
      id: {type: 'integer'},
      value: {type: 'string'}
    }
  };
  static relationMappings = {
    children: {
      relation: MoronModel.OneToManyRelation,
      modelClass: Person,
      join: {
        from: 'Person.id',
        to: 'Person.parentId'
      }
    }
  }
}
```

Static properties are actually an ES7 feature. You have to enable the `es7.classProperties` feature in Babel. If you don't want to use experimental features you can always assign the needed static properties to the constructor like in ES5, but that kind of takes all the fun out of using classes.

I could't get Babel compile any code that contained the `await` keyword even when I enabled the `es7.asyncFunctions` feature. Therefore I couldn't test if the asynchronous functions worked. They should work with promises though so I'll test them as soon as I get babel working.

**Comment by koskimas** [comment]
I just added an ES7 example project to the `examples` folder. You can run the example server using the commands from the [getting started](https://github.com/Vincit/moron.js#getting-started) section of the readme. Check out [this](https://github.com/Vincit/moron.js/blob/master/examples/express-es7/api.js) ES7 goodness!

**Comment by novacrazy** [comment]
So I've been working with Babel and ES6/ES7 features for a couple months now. If you do use async/await in your code I'd highly recommend using the Bluebird Coroutines transform instead of the normal async/await transformer that uses regenerator. 

If you are yielding things other than promises directly, I have a good example for a bluebird yield handler [Here](https://github.com/novacrazy/scriptor/blob/master/src/yield_handler.js).

**Comment by koskimas** [comment]
Thanks for the tip. Are there other reasons besides performance for avoiding the regenerator version?

**Comment by novacrazy** [comment]
I use Bluebird for promises throughout my entire application, so it provides a bit better integration with that. Though mostly because it does allow adding the additional yield handlers. Normally with ES7 async/await functions you can only await Promises, not arrays of promises, generators, or generators that produce arrays of promises, etc. Adding the yield handler allows you to await basically anything without worrying about it. Plus having Bluebird all the way and enabling long stack traces offers much more verbose stack traces that can help with debugging. 

However, Bluebird coroutines do require native ES6 generators, but that's not too much of an issue nowadays with io.js taking over everything. If you do plan on targeting old and potentially insecure (pre-0.12) versions of node, then stick with the regenerator version.

**Comment by novacrazy** [comment]
To make things easier on you, and myself, I went ahead and put those yield handlers into their own library. See [bluebird-co](https://github.com/novacrazy/bluebird-co) for more info.
